Add general setting to configure session timeout
airsonic-advanced/airsonic-advanced pull request #753
Opened 2022-01-27 00:14 UTC by NoItemName

Enables session timeout configuration. This feature doesn't override _remember me_ check.
Implements [#619](https://github.com/airsonic-advanced/airsonic-advanced/issues/619)

2022-01-27 12:36 UTC, randomnicode commented
Does this spring config not suffice?
`server.servlet.session.timeout=60s`
specified in https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.servlet.session.timeout

It's a good idea to just use the spring property without overriding manually in a custom config class. okay to have a ui for specifying it. We will provide PR comments accordingly

2022-01-27 12:53 UTC, randomnicode requested changes

2022-01-27 12:53 UTC, randomnicode commented on airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
> +    private static final String KEY_SESSION_TIMEOUT_MESSAGE = "SessionTimeout";
Probably should be named `server.servlet.session.timeout` so it overrides the spring boot value

2022-01-27 12:53 UTC, randomnicode commented on airsonic-main/src/main/java/org/airsonic/player/service/SettingsService.java
> +    private static final int DEFAULT_SESSION_TIMEOUT_MINUTES = 60;
Maybe a String or Duration?

org.springframework.boot.web.servlet.server.Session details the timeout field as a Duration

default is 30m it seems

2022-01-27 12:53 UTC, randomnicode commented on airsonic-main/src/main/java/org/airsonic/player/spring/CustomSessionListener.java
> +public class CustomSessionListener implements HttpSessionListener {
this class isn't needed

2022-01-27 12:53 UTC, randomnicode commented on airsonic-main/src/main/resources/org/airsonic/player/i18n/ResourceBundle_en.properties
> +generalsettings.sessiontimeout=Session timeout in minutes. Changes will take effect on a new login
if it's a string, session timeout will be a duration string, if no postfix then in seconds.
also not sure when changes take effect with the spring boot var, maybe at application restart?

2022-01-27 12:53 UTC, randomnicode commented on airsonic-main/src/main/java/org/airsonic/player/command/GeneralSettingsCommand.java
> +    public Integer getSessionTimeout() {
string or duration?

2022-01-27 21:51 UTC, NoItemName commented
Thanks for the feedback, i will work on the changes!

2022-02-17 09:39 UTC, randomnicode approved these changes

2022-02-17 09:40 UTC, merged